// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"github.com/safatanc/gsalt-core/internal/app/deliveries"
	"github.com/safatanc/gsalt-core/internal/app/middlewares"
	"github.com/safatanc/gsalt-core/internal/app/services"
	"github.com/safatanc/gsalt-core/internal/infrastructures"
)

// Injectors from injector.go:

// InitializeApplication initializes the application with all its dependencies
func InitializeApplication() (*Application, error) {
	db := infrastructures.NewDatabase()
	validator := infrastructures.NewValidator()
	connectService := services.NewConnectService()
	accountService := services.NewAccountService(db, validator, connectService)
	authMiddleware := middlewares.NewAuthMiddleware(connectService, accountService)
	accountHandler := deliveries.NewAccountHandler(accountService, authMiddleware)
	transactionService := services.NewTransactionService(db, validator, accountService)
	transactionHandler := deliveries.NewTransactionHandler(transactionService, authMiddleware)
	voucherService := services.NewVoucherService(db, validator)
	voucherHandler := deliveries.NewVoucherHandler(voucherService, authMiddleware)
	voucherRedemptionService := services.NewVoucherRedemptionService(db, validator, voucherService, accountService, transactionService)
	voucherRedemptionHandler := deliveries.NewVoucherRedemptionHandler(voucherRedemptionService, authMiddleware)
	application := &Application{
		AccountHandler:           accountHandler,
		TransactionHandler:       transactionHandler,
		VoucherHandler:           voucherHandler,
		VoucherRedemptionHandler: voucherRedemptionHandler,
	}
	return application, nil
}

// injector.go:

// Application represents the main application container for gsalt-core
type Application struct {
	AccountHandler           *deliveries.AccountHandler
	TransactionHandler       *deliveries.TransactionHandler
	VoucherHandler           *deliveries.VoucherHandler
	VoucherRedemptionHandler *deliveries.VoucherRedemptionHandler
}

// RegisterRoutes registers all application routes using a Fiber router
func (app *Application) RegisterRoutes(router fiber.Router) {

	app.AccountHandler.RegisterRoutes(router)
	app.TransactionHandler.RegisterRoutes(router)
	app.VoucherHandler.RegisterRoutes(router)
	app.VoucherRedemptionHandler.RegisterRoutes(router)
}

// Infrastructure providers
var infrastructureSet = wire.NewSet(infrastructures.NewDatabase, infrastructures.NewValidator)

// Service providers
var serviceSet = wire.NewSet(services.NewConnectService, services.NewAccountService, services.NewTransactionService, services.NewVoucherService, services.NewVoucherRedemptionService)

// Middleware providers
var middlewareSet = wire.NewSet(middlewares.NewAuthMiddleware)

// Handler providers
var handlerSet = wire.NewSet(deliveries.NewAccountHandler, deliveries.NewTransactionHandler, deliveries.NewVoucherHandler, deliveries.NewVoucherRedemptionHandler, wire.Struct(new(Application), "*"))
